name: colibri
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+5

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  colibri_shared:
    #path: ../colibri_shared
    git:
      url: https://github.com/Alejandroem/colibri_shared
      ref: master

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  location: ^6.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  font_awesome_flutter: ^10.7.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  intl_phone_number_input: ^0.7.4
  cloud_firestore: ^5.2.0
  google_maps_flutter: ^2.7.1
  camera: ^0.11.0+1
  carousel_slider: ^5.0.0
  flutter_stripe: ^11.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  firebase_app_check: ^0.3.1+2
  flutter_i18n: ^0.36.0
  firebase_messaging: ^15.1.3
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  keep_aspect_ratio: true
  remove_alpha: true

flutter_native_splash:
  color: "#fd167d"
  image: "assets/images/splash.png"
  background_image: "assets/images/background.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/splash.png"
    icon_background_color: "#fd167d"
    image_dark: "assets/images/splash.png"
    icon_background_color_dark: "#fd167d"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/
