// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfPIGYqWdV-mfMdFsnxUlGrGjy5uHuosw',
    appId: '1:45560064767:android:4de566a312de97f78bfaca',
    messagingSenderId: '45560064767',
    projectId: 'colibri-173d3',
    storageBucket: 'colibri-173d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAimIB1y3JLEPInN-PleEWmDTbWkGhkPUU',
    appId: '1:45560064767:ios:d91c5c44d83a46cc8bfaca',
    messagingSenderId: '45560064767',
    projectId: 'colibri-173d3',
    storageBucket: 'colibri-173d3.appspot.com',
    iosBundleId: 'com.colibri.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAimIB1y3JLEPInN-PleEWmDTbWkGhkPUU',
    appId: '1:45560064767:ios:1982726999ca12d78bfaca',
    messagingSenderId: '45560064767',
    projectId: 'colibri-173d3',
    storageBucket: 'colibri-173d3.appspot.com',
    iosBundleId: 'com.example.colibri',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwqLCNtxbDVtBvPNUTovU3FFwRjvq7SI',
    appId: '1:45560064767:web:2bad62a0d632e1178bfaca',
    messagingSenderId: '45560064767',
    projectId: 'colibri-173d3',
    authDomain: 'colibri-173d3.firebaseapp.com',
    storageBucket: 'colibri-173d3.appspot.com',
    measurementId: 'G-NFR28WSBCF',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTwqLCNtxbDVtBvPNUTovU3FFwRjvq7SI',
    appId: '1:45560064767:web:0e994ca8a669566f8bfaca',
    messagingSenderId: '45560064767',
    projectId: 'colibri-173d3',
    authDomain: 'colibri-173d3.firebaseapp.com',
    storageBucket: 'colibri-173d3.appspot.com',
    measurementId: 'G-E0DVV7QZN3',
  );

}